apiVersion: v1
kind: Service
metadata:
  name: karpenter-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      targetPort: metrics
  selector:
    karpenter: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controller.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      karpenter: controller
  template:
    metadata:
      labels:
        karpenter: controller
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: manager
          image: {{ .Values.controller.image }}
        {{- if .Values.controller.defaultInstanceProfile }}
          args:
            - -default-instance-profile={{ .Values.controller.defaultInstanceProfile }}
        {{- end }}
        {{- if .Values.controller.resources }}
          resources: {{ toYaml .Values.controller.resources | nindent 12 }}
        {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
            - name: health-probe
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.controller.clusterName }}
            - name: CLUSTER_ENDPOINT
              value: {{ .Values.controller.clusterEndpoint }}
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .Values.controller.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      # https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8#issuecomment-636888074 - not needed in k8s versions 1.19+
      securityContext:
        fsGroup: 1000
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- if .Values.controller.affinity }}
          {{- toYaml .Values.controller.affinity | nindent 8 }}
        {{- else }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
        {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
